"""
Load financial data from parquet files into PostgreSQL.

Strategy: TRUNCATE each table, then INSERT from parquet.
- Skips the `id` column (auto-generated by DB serial).
- Adds missing columns to the DB if parquet has new ones.
- Reads parquet from data/raw/.
"""

import os
import sys
import logging
from pathlib import Path

import pandas as pd
import psycopg2
from psycopg2.extras import execute_values
from psycopg2 import sql

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger(__name__)

# ── Config ─────────────────────────────────────────────────────────────────────
DB_URL = os.getenv("FINANCIAL_DB_URL", "postgresql://galaxymacbook@localhost:5432/financial_db")
RAW_DIR = Path(__file__).parent.parent / "data" / "raw"

# Tables to load, in dependency order (no FK issues for this schema, but explicit is safer)
TABLES = [
    "anomalies",
    "channel_payment",
    "daily_master",
    "daily_product_channel",
    "daily_unique_users",
    "daily_user_partner",
    "financial_internal",
    "hourly_pattern_daily",
    "product_price_list",
    "product_summary",
]

# Columns generated by DB — never write these from parquet
AUTO_COLUMNS = {"id"}

# For tables with unique constraints on non-id columns, deduplicate on these keys
# keeping the last row (most recent value wins)
DEDUP_KEYS: dict[str, list[str]] = {
    "product_price_list": ["product_id"],
}


def get_db_columns(cur, table: str) -> set[str]:
    cur.execute(
        """
        SELECT column_name FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
        """,
        (table,),
    )
    return {row[0] for row in cur.fetchall()}


def add_missing_columns(cur, table: str, new_cols: list[tuple[str, str]]) -> None:
    """ALTER TABLE to add columns that exist in parquet but not in DB."""
    for col_name, pg_type in new_cols:
        log.info("  ALTER TABLE %s ADD COLUMN %s %s", table, col_name, pg_type)
        cur.execute(
            sql.SQL("ALTER TABLE {} ADD COLUMN IF NOT EXISTS {} {}").format(
                sql.Identifier(table),
                sql.Identifier(col_name),
                sql.SQL(pg_type),
            )
        )


def infer_pg_type(series: pd.Series) -> str:
    dtype = series.dtype
    if pd.api.types.is_integer_dtype(dtype):
        return "BIGINT"
    if pd.api.types.is_float_dtype(dtype):
        return "DOUBLE PRECISION"
    if pd.api.types.is_bool_dtype(dtype):
        return "BOOLEAN"
    return "TEXT"


def load_table(conn, table: str, df: pd.DataFrame) -> None:
    cur = conn.cursor()

    db_cols = get_db_columns(cur, table)
    parquet_cols = set(df.columns)
    writable_cols = parquet_cols - AUTO_COLUMNS

    # Add columns that are in parquet but missing from DB
    missing = writable_cols - db_cols
    if missing:
        new_col_defs = [(c, infer_pg_type(df[c])) for c in sorted(missing)]
        log.warning("  New columns in parquet not in DB: %s", [c for c, _ in new_col_defs])
        add_missing_columns(cur, table, new_col_defs)
        conn.commit()
        db_cols = get_db_columns(cur, table)  # refresh

    # Only load columns that exist in both parquet and DB (excluding auto cols)
    cols_to_load = sorted(writable_cols & db_cols)
    df_load = df[cols_to_load].copy()

    # Replace NaN with None so psycopg2 writes NULL
    df_load = df_load.where(pd.notna(df_load), other=None)

    log.info("  TRUNCATE %s", table)
    cur.execute(sql.SQL("TRUNCATE TABLE {} RESTART IDENTITY CASCADE").format(sql.Identifier(table)))

    log.info("  INSERT %d rows into %s (%d cols)", len(df_load), table, len(cols_to_load))
    col_identifiers = sql.SQL(", ").join(map(sql.Identifier, cols_to_load))
    insert_stmt = sql.SQL("INSERT INTO {} ({}) VALUES %s").format(
        sql.Identifier(table), col_identifiers
    )
    rows = [tuple(row) for row in df_load.itertuples(index=False)]
    execute_values(cur, insert_stmt, rows, page_size=1000)

    conn.commit()
    cur.close()


def main() -> None:
    log.info("Connecting to: %s", DB_URL.split("@")[-1])  # hide credentials
    conn = psycopg2.connect(DB_URL)

    errors: list[str] = []
    for table in TABLES:
        parquet_path = RAW_DIR / f"{table}.parquet"
        if not parquet_path.exists():
            log.warning("SKIP %s — parquet not found at %s", table, parquet_path)
            continue

        log.info("Loading %s ...", table)
        try:
            df = pd.read_parquet(parquet_path)
            if table in DEDUP_KEYS:
                before = len(df)
                df = df.drop_duplicates(subset=DEDUP_KEYS[table], keep="last")
                dropped = before - len(df)
                if dropped:
                    log.warning("  Deduplicated %d rows on %s", dropped, DEDUP_KEYS[table])
            load_table(conn, table, df)
            log.info("  OK — %d rows loaded", len(df))
        except Exception as e:
            log.error("  FAILED %s: %s", table, e)
            conn.rollback()
            errors.append(f"{table}: {e}")

    conn.close()

    if errors:
        log.error("\n%d table(s) failed:", len(errors))
        for err in errors:
            log.error("  %s", err)
        sys.exit(1)
    else:
        log.info("\nAll tables loaded successfully.")


if __name__ == "__main__":
    main()
